BloodBank/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^beforeSearch/',views.beforeSearch,name='beforeSearch'),
    url(r'^search/',views.search,name='search'),
    url('', include('django.contrib.auth.urls')),

    url(r'^donorRegistration/',views.donorRegistration,name='donorRegistration'),
    url(r'^getDonorRegInfo/',views.getDonorRegInfo,name='getDonorRegInfo'),

    url(r'^login/',auth_views.login,name='login'),
    url(r'^logout/',auth_views.logout,name='logout'),
    url(r'^newUser/',views.newUser,name='newUser'),
    url(r'^staff/',views.staff,name='staff'),

    url(r'^insertStock/',views.insertStock,name='insertStock'),
    url(r'^stockInfo/',views.stockInfo,name='stockInfo'),

    url(r'^donorInfo/',views.donorInfo,name='donorInfo'),
    url(r'^getDonorInfo/',views.getDonorInfo,name='getDonorInfo'),
    url(r'^getNewUserInfo/',views.getNewUserInfo,name='getNewUserInfo'),

]

BloodDonationBank/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bloodbank/', include('BloodBank.urls',namespace = "bloodbank")),
]

BloodBank/models.py
from django.db import models

# Create your models here.
class Donor(models.Model):
    Name = models.CharField(max_length = 64)
    Age = models.IntegerField()
    Gender = models.CharField(max_length=10)
    Blood_Grp = models.CharField(max_length=10)
    PhoneNo = models.IntegerField()

class Hospital(models.Model):
    Hospital_Code = models.IntegerField(db_index=True)
    Hos_Name = models.CharField(max_length=64)
    Blood_Grp = models.CharField(db_index=True,max_length=10)
    stock = models.IntegerField()

    Hos_Address = models.CharField(max_length=64)
    Hos_PhoneNo = models.IntegerField()
    Hos_Email = models.EmailField(max_length=64)

class UserDetail(models.Model):
    Hos_Code = models.IntegerField(db_index=True,primary_key=True)
    User_Name = models.CharField(max_length=100)

BloodBank/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from .models import Donor,Hospital,UserDetail
import time
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User



def index(request):
    context = {
        "Donor" : Donor.objects.all()
    }
    return render(request,"BloodBank/index.html",context)

def search(request):
    context = {
        "searchResult" :Hospital.objects.filter(Blood_Grp=request.POST.get('select')),
        "donorResult" :Donor.objects.filter(Blood_Grp=request.POST.get('select'))

    }
    return render(request,"BloodBank/beforeSearch.html",context)
def beforeSearch(request):
    return render(request,"BloodBank/beforeSearch.html")

def staff(request):
    return render(request,"BloodBank/staff.html")

def insertStock(request):
    return render(request,"BloodBank/insertStock.html")

def donorInfo(request):
    return render(request,"BloodBank/donorInfo.html")

def stockInfo(request):
    validation = []
    grp = request.GET['grp']
    stock = int(request.GET['stock'])
    code = request.GET['code']
    validation.append(grp)
    validation.append(stock)
    validation.append(code)
    if '' in validation:
        message = 'You submitted an empty form.'
        return HttpResponse(message)

    try:
        try:
            user = User.objects.get(username=request.user.get_username)
            data = UserDetail.objects.get(Hos_Code=code,User_Name= user)
        except Exception as e:
            message="Check the Enter data"
            return HttpResponse(message)
        if data:
            insertResult=Hospital.objects.filter(Blood_Grp=grp,Hospital_Code=code)
            w = insertResult.first()
            w.stock = stock + w.stock
            w.save()
            message = 'Succeffull'
            context = {
            "result" : Hospital.objects.filter(Hospital_Code=code)
            }

            return render(request,"BloodBank/insertStock.html",context)
    except AttributeError as e:
        message = "Check entered data"
        return HttpResponse(message)

def getDonorInfo(request):
    donorBloodGrp = request.GET['donorBloodGrp']
    if 'donorBloodGrp' in request.GET:
        context = {
            "donorResult" :Donor.objects.filter(Blood_Grp=request.GET['donorBloodGrp']),
            "donorBloodGrp":donorBloodGrp

        }
        return render(request,"BloodBank/donorInfo.html",context)
    else:
        message = 'You submitted an empty form.'
        return HttpResponse(message)

def newUser(request):
    joinedDate = str(request.user.date_joined)
    first = joinedDate.split(" ")
    time1 = first[1].split(":")

    join_date = str(first[0])
    join_time = int(time1[0])*60 + int(time1[1])
    pc_time = time.ctime().split(" ")[3].split(":")

    pc1_time = int(pc_time[0])*60 + int(pc_time[1])
    pc1_date = str(datetime.datetime.today().strftime('%Y-%m-%d'))

    active = request.user.is_active
    staff = request.user.is_staff

    user = User.objects.get(username=request.user.get_username)
    if not staff:
        if(join_date == pc1_date):
            if (join_time <= pc1_time):
                return render(request,"BloodBank/newUser.html")
    else:
        return render(request,"BloodBank/staff.html")

def getNewUserInfo(request):
    C = request.POST["Hospital_Code"]
    N = request.POST["Hos_Name"]

    G1 = request.POST["1"]
    S1 = request.POST["Stock1"]

    G2 = request.POST["2"]
    S2 = request.POST["Stock2"]

    G3 = request.POST["3"]
    S3 = request.POST["Stock3"]

    G4 = request.POST["4"]
    S4 = request.POST["Stock4"]

    G5 = request.POST["5"]
    S5 = request.POST["Stock5"]

    G6 = request.POST["6"]
    S6 = request.POST["Stock6"]

    G7 = request.POST["7"]
    S7 = request.POST["Stock7"]

    G8 = request.POST["8"]
    S8 = request.POST["Stock8"]

    A = request.POST["Hos_Address"]
    P = request.POST["Hos_PhoneNo"]
    E = request.POST["Hos_Email"]

    user = User.objects.get(username=request.user.get_username)
    try:
        o = UserDetail.objects.create(Hos_Code=C,User_Name=user)
    except IntegrityError:
        message = "Hospital Code already present"
        return HttpResponse(message)
    try:
        insertResult=Hospital.objects.create(Hospital_Code=C ,Hos_Name=N ,Blood_Grp=G1 ,stock=S1 ,Hos_Address=A ,Hos_PhoneNo=P ,Hos_Email=E)
        insertResult=Hospital.objects.create(Hospital_Code=C ,Hos_Name=N ,Blood_Grp=G2 ,stock=S2 ,Hos_Address=A ,Hos_PhoneNo=P ,Hos_Email=E)

        insertResult=Hospital.objects.create(Hospital_Code=C ,Hos_Name=N ,Blood_Grp=G3 ,stock=S3 ,Hos_Address=A ,Hos_PhoneNo=P ,Hos_Email=E)
        insertResult=Hospital.objects.create(Hospital_Code=C ,Hos_Name=N ,Blood_Grp=G4 ,stock=S4 ,Hos_Address=A ,Hos_PhoneNo=P ,Hos_Email=E)

        insertResult=Hospital.objects.create(Hospital_Code=C ,Hos_Name=N ,Blood_Grp=G5 ,stock=S5 ,Hos_Address=A ,Hos_PhoneNo=P ,Hos_Email=E)
        insertResult=Hospital.objects.create(Hospital_Code=C ,Hos_Name=N ,Blood_Grp=G6 ,stock=S6 ,Hos_Address=A ,Hos_PhoneNo=P ,Hos_Email=E)

        insertResult=Hospital.objects.create(Hospital_Code=C ,Hos_Name=N ,Blood_Grp=G7 ,stock=S7 ,Hos_Address=A ,Hos_PhoneNo=P ,Hos_Email=E)
        insertResult=Hospital.objects.create(Hospital_Code=C ,Hos_Name=N ,Blood_Grp=G8 ,stock=S8 ,Hos_Address=A ,Hos_PhoneNo=P ,Hos_Email=E)

        message = 'Succeffull'
        user = User.objects.get(username=request.user.get_username)
        user.is_staff = True
        user.save()
        context = {
        "thank":"Thank You",
        "result":"Insert New User Successfully "

        }
        return render(request,"BloodBank/newUser.html",context)
    except AttributeError as e:
        message = "Check entered data"
        return HttpResponse(message)


def donorRegistration(request):
    n=[]
    for i in range(17,71):
        n.append(i)
    context = {
    "n":n
    }
    return render(request,"BloodBank/donorRegistration.html",context)

def getDonorRegInfo(request):
    N = request.POST["Reg_Name"]
    A = request.POST.get("Reg_Age")

    G = request.POST.get("Reg_Gender")
    Grp = request.POST.get("Reg_grp")

    C = request.POST["Reg_PhoneNo"]

    n=[]
    for i in range(17,71):
        n.append(i)
    try:
        insertResult=Donor.objects.create(Name=N, Age=A, Gender=G, Blood_Grp=Grp, PhoneNo=C )
        context = {
        "Result":"Your Donation Save Life.",
        "thank" :"Thank You",
        "n":n
        }
        return render(request,"BloodBank/donorRegistration.html",context)
    except AttributeError as e:
        message = "Check entered data"
        return HttpResponse(message)

BloodBank/templates/BloodBank/beforeSearch.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SearchBlood</title>
    <link rel="stylesheet" type="text/css" href={% static 'BloodBank/3layout.css'  %}>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
      <header>
          <h1>Search Query Result</h1>
      </header>

      <div class="row">
        <div class="column left">
          <h2>Enter Blood Group</h2>
          <form action="{% url 'bloodbank:search' %}" method="POST">{% csrf_token %}
              <select name = "select">
                  <option value="A+">A+</option>
                  <option value="A-">A-</option>
                  <option value="B+">B+</option>
                  <option value="B-">B-</option>
                  <option value="O+">O+</option>
                  <option value="O-">O-</option>
                  <option value="AB+">AB+</option>
                  <option value="AB-">AB-</option>
              </select>

              <input id ="submit" type="submit" value="Search">
          </form>

        </div>
        <div class="column middle">
          <h3>Result </h3>
          <table border="1" align="center">
            <tr>
                <th>Blood Grp</th>
                <th>Hospital</th>
                <th>Stocks</th>
                <th>Address</th>
                <th>Contact</th>
            </tr>
            {% for result in searchResult %}
            <tr>
                <th> {{ result.Blood_Grp }} </th>
                <th> {{ result.Hos_Name }} </th>
                <th> {{ result.stock }} </th>
                <th> {{ result.Hos_Address }} </th>
                <th> {{ result.Hos_PhoneNo }} </th>

            </tr>

            {% endfor %}
          </table>
        </div>
        <div class="column right">
          <h4>Result </h4>
          <table border="1" align="center">
            <tr>
                <th>Name</th>
                <th>Gender</th>
                <th>Contact</th>
            </tr>
            {% for result in donorResult %}
            <tr>
                <th> {{ result.Name }} </th>
                <th> {{ result.Gender }} </th>
                <th> {{ result.PhoneNo }} </th>
            </tr>

            {% endfor %}
          </table>
        </div>
      </div>

  </body>
</html>

BloodBank/templates/BloodBank/donorInfo.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>DonorInfo</title>
    <link rel="stylesheet" type="text/css" href={% static 'BloodBank/3layout.css'  %}>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
        <h1>Donor Information</h1>
    </header>
    <div class="row">
      <div class="column left">
        <a href="{% url 'bloodbank:logout' %}" align="right"><b>Logout</b></a><br>

        <form method="GET" action="{% url 'bloodbank:getDonorInfo' %}">
            <h2>Enter the Blood Group</h2>
            <select name = "donorBloodGrp">
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
            </select>
            <input type="submit" value="Submit">
        </form>
        <br><br><br>

        <form action="{% url 'bloodbank:staff' %}" method="GET">
            <input id ="submit" type="submit" value="Go To Home">
        </form>
      </div>
      <div class="column middle">
        <h3> Blood Group {{ donorBloodGrp }} List</h3>
        <table border="1" align="center">
          <tr>
              <th>Name</th>
              <th>Gender</th>
              <th>Contact</th>
          </tr>
          {% for result in donorResult %}
          <tr>
              <th> {{ result.Name }} </th>
              <th> {{ result.Gender }} </th>
              <th> {{ result.PhoneNo }} </th>
          </tr>

          {% endfor %}
        </table>

      </div>
      <div class="column right">

      </div>
    </div>
  </body>
</html>

BloodBank/templates/BloodBank/donorRegistration.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>Registration</title>
    <link rel="stylesheet" type="text/css" href={% static 'BloodBank/3layout.css'  %}>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
      <header>
          <h1>Register YourSelf</h1>
      </header>

      <div class="row">
        <div class="column left">

          <form method="POST" action="{% url 'bloodbank:getDonorRegInfo' %}">{% csrf_token %}
              <table align="center">
                <tr>
                    <th><label>Name:</label></th>
                    <th><input type="text" placeholder="Name" name="Reg_Name" pattern="[a-zA-Z]{1,50}" title="Enter A-za-z less than 50 character"  required></th>
                </tr>
                <br>
                <tr>
                </tr>
                <tr>
                    <th><label>Age:</label></th>
                    <th>
                      <select name = "Reg_Age">
                        {% for i in n %}
                        <option value="{{i}}">{{i}}</option>
                        {% endfor %}
                      </select>
                    </th>

                </tr>
                <tr>
                </tr>
                <tr>
                    <th><label>Gender:</label></th>
                    <th>
                      <select name = "Reg_Gender">
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                        <option value="Other">Other</option>
                      </select>
                  </th>
                </tr>
                <tr>
                </tr>
                <tr>
                    <th><label>Blood Group:</label></th>
                    <th>
                      <select name = "Reg_grp">
                        <option value="A+">A+</option>
                        <option value="A-">A-</option>
                        <option value="B+">B+</option>
                        <option value="B-">B-</option>
                        <option value="O+">O+</option>
                        <option value="O-">O-</option>
                        <option value="AB+">AB+</option>
                        <option value="AB-">AB-</option>
                      </select>
                    </th>
                </tr>
                <tr>
                </tr>
                <tr>
                    <th><label>Contact:</label></th>
                    <th><input type="text" placeholder="Contact" name="Reg_PhoneNo" pattern="[0-9]{10}" title="Only 10 digit number" required></th>
                </tr>
              </table><br><br>
                  <input type="submit" value="Submit"><br><br><br>
            </form>
            <form action="{% url 'bloodbank:index' %}" method="GET">
                <input id ="submit" type="submit" value="Go To Home">
            </form>
        </div>
        <div class="column middle">
          <h1> {{Result}}</h1><br>
          <h2> {{thank}}</h2><br>
        </div>
        <div class="column right">


        </div>
      </div>
  </body>
</html>

BloodBank/templates/BloodBank/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Index</title>
    <link rel="stylesheet" type="text/css" href={% static 'BloodBank/layout.css'  %}>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
      <div id = "header">
        <header>
          <h1>Blood Bank</h1>
        </header>
      </div>

      <section>
        <nav>
          <ul>
            <li><a href="{% url 'bloodbank:beforeSearch' %}" >SearchBlood</a></li>
          </ul>
        </nav>

        <article>
          <h1>Search</h1>
          <p>“Sometimes money cannot save life but donated blood can!”</p>
          <p>“Fighting you's the only reward I want,' I said, 'for saving your life.”</p>
        </article>

        <nav>
          <ul>
            <li><a href="{% url 'bloodbank:donorRegistration' %}" >Registration Donor</a></li>
          </ul>
        </nav>

        <article>
          <h1>Save Life</h1>
          <p>“Someone’s blood saved my life and made my mom smile – was that you?”</p>
          <p>“The Blood Donor of today may be recipient of tomorrow.”</p>
        </article>

        <nav>
          <ul>
            <li><a href="{% url 'bloodbank:login' %}" >Login</a></li>
          </ul>
        </nav>

        <article>
          <h1>Login</h1>
          <p>“It’s a great honor,” said Fedyor. “To save a life. You saved many.” </p>
          <p>“We were meant to rescue each other, not cut down the forest to rescue one.”</p>
        </article>
      </section>

  </body>
</html>

BloodBank/templates/BloodBank/insertStock.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>insertStock</title>
    <link rel="stylesheet" type="text/css" href={% static 'BloodBank/3layout.css'  %}>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
        <h1>Insert Stock</h1>
    </header>
    <div class="row">
      <div class="column left">
        <a href="{% url 'bloodbank:logout' %}" align="right"><b>Logout</b></a>
        <br><br>
        <form action="{% url 'bloodbank:stockInfo' %}" method="GET">
          <table align="center">
            <tr>
              <th><label>Blood Group:</label></th>
              <th>
                <select name = "grp">
                  <option value="A+">A+</option>
                  <option value="A-">A-</option>
                  <option value="B+">B+</option>
                  <option value="B-">B-</option>
                  <option value="O+">O+</option>
                  <option value="O-">O-</option>
                  <option value="AB+">AB+</option>
                  <option value="AB-">AB-</option>
                </select>
            </tr>
            <tr>
            </tr>
            <tr>
              <th><label>Stocks :</label></th>
              <th><input type="text" placeholder="Stocks" name="stock" pattern="[0-9]{1,}" title="Only 10 digit number" required></th>
            </tr>
            <tr>
            </tr>
            <tr>
              <th><label>Hospital Code:</label></th>
              <th><input type="text" placeholder="Hospital Code:" name="code" pattern="[0-9]{1,}" title="Enter Only number" required></th>
            </tr>
            <tr>
            </tr>
          </table><br><br>
          <input type="submit" value="Submit">
        </form><br><br><br>

        <form action="{% url 'bloodbank:staff' %}" method="GET">
            <input id ="submit" type="submit" value="Go To Home">
        </form>
      </div>
      <div class="column middle">
        <h3> Insert data Successfully : Update Database </h3>
        <table border="1" align="center">
          <tr>
              <th>Code</th>
              <th>Name</th>
              <th>Blood_Grp</th>
              <th>Stock</th>
          </tr>
          {% for data in result %}
          <tr>
              <th> {{ data.Hospital_Code }} </th>
              <th> {{ data.Hos_Name }} </th>
              <th> {{ data.Blood_Grp }} </th>
              <th> {{ data.stock }} </th>
          </tr>

          {% endfor %}
        </table>
      </div>
      <div class="column right">

      </div>
    </div>
  </body>
</html>

BloodBank/templates/BloodBank/newUser.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>NewUser</title>
    <link rel="stylesheet" type="text/css" href={% static 'BloodBank/3layout.css'  %}>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
        <h1>New User</h1>
    </header>
    <div class="row">
      <div class="column left">
        <a href="{% url 'bloodbank:logout' %}" align="right"><b>Logout</b></a>
        <br><br>
        <form method="POST" action="{% url 'bloodbank:getNewUserInfo' %}">{% csrf_token %}
            <h2>Enter the Hospital Information</h2>
            <table>
              <tr>
                <th><label>Code:</label></th>
                <th><input type="text" placeholder="Code" name="Hospital_Code" pattern="[0-9]{1,}" title="Enter Only number"  required></th>
              </tr>
              <tr>
                <th><label>Name:</label></th>
                <th><input type="text" placeholder="Name" name="Hos_Name" pattern="[a-zA-Z]{1,}" title="Enter Alphabet only" required></th>
              </tr>
              <tr>
                <th><label>Address:</label></th>
                <th><input type="text" placeholder="Address" name="Hos_Address" required></th>
              </tr>
              <tr>
                <th><label>Contact:</label></th>
                <th><input type="text" placeholder="Contact" name="Hos_PhoneNo" pattern="[0-9]{10}" title="Only 10 digit number" required></th>
              </tr>
              <tr>
                <th><label>Email:</label></th>
                <th><input type="text" placeholder="Email" name="Hos_Email" required></th>
              </tr>
            </table><br><br>
            <table>
              <tr>
                  <th><label>A+ Info:</label></th>
                  <th><input type="text"  name="1" value="A+"></th>
                  <th><input type="text" placeholder="Stock" name="Stock1" pattern="[0-9]{1,}" title="Only number" required></th>
              </tr>
              <tr>
                  <th><label>A- Info:</label></th>
                  <th><input type="text"  name="2" value="A-"></th>
                  <th><input type="text" placeholder="Stock" name="Stock2" pattern="[0-9]{1,}" title="Only number" required></th>
              </tr>
              <tr>
                  <th><label>B+ Info:</label></th>
                  <th><input type="text"  name="3" value="B+"></th>
                  <th><input type="text" placeholder="Stock" name="Stock3" pattern="[0-9]{1,}" title="Only number" required></th>
              </tr>
              <tr>
                  <th><label>B- Info:</label></th>
                  <th><input type="text"  name="4" value="B-"></th>
                  <th><input type="text" placeholder="Stock" name="Stock4" pattern="[0-9]{1,}" title="Only number" required></th>
              </tr>
              <tr>
                  <th><label>O+ Info:</label></th>
                  <th><input type="text"  name="5" value="O+"></th>
                  <th><input type="text" placeholder="Stock" name="Stock5" pattern="[0-9]{1,}" title="Only number" required></th>
              </tr>
              <tr>
                  <th><label>O- Info:</label></th>
                  <th><input type="text"  name="6" value="O-"></th>
                  <th><input type="text" placeholder="Stock" name="Stock6" pattern="[0-9]{1,}" title="Only number"  required></th>
              </tr>
              <tr>
                  <th><label>AB+ Info:</label></th>
                  <th><input type="text"  name="7" value="AB+"></th>
                  <th><input type="text" placeholder="Stock" name="Stock7" pattern="[0-9]{1,}" title="Only number" required></th>
              </tr>
              <tr>
                  <th><label>AB- Info:</label></th>
                  <th><input type="text"  name="8" value="AB-"></th>
                  <th><input type="text" placeholder="Stock" name="Stock8" pattern="[0-9]{1,}" title="Only number" required></th>
              </tr>
            </table><br>
            <input type="submit" value="Submit">
        </form><br><br><br>
      </div>
      <div class="column middle">
        <h1> {{result}}</h1><br>
        <h2> {{thank}}</h2><br>

      </div>
      <div class="column right">


      </div>
    </div>
  </body>
</html>

BloodBank/templates/BloodBank/staff.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>Staff</title>
    <link rel="stylesheet" type="text/css" href={% static 'BloodBank/layout.css'  %}>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
      <h1>Staff Login</h1>
    </header>
    <section>
      <nav>
        <a href="{% url 'bloodbank:logout' %}" align="right"><b>Logout</b></a>
        <ul>
          <li>
            <form method="post" action="{% url 'bloodbank:beforeSearch' %}">{% csrf_token %}
            <input type="submit" id="Insert" value="SearchBlood"></input>
          </form>
        </li>
      </ul>
      </nav>

      <article>
        <h1>Search</h1>
        <p>“Sometimes money cannot save life but donated blood can!”</p>
        <p>“Fighting you's the only reward I want,' I said, 'for saving your life.”</p>
      </article>

      <nav>
        <ul>
          <li>
            <form method="post" action="{% url 'bloodbank:insertStock' %}">{% csrf_token %}
            <input type="submit" id="Insert" value="InsertStock"></input>
          </form>
        </li>
      </ul>
      </nav>

      <article>
        <h1>Save Life</h1>
        <p>“Someone’s blood saved my life and made my mom smile – was that you?”</p>
        <p>“The Blood Donor of today may be recipient of tomorrow.”</p>
      </article>

      <nav>
        <ul>
          <li>
            <form method="post" action="{% url 'bloodbank:donorInfo' %}" >{% csrf_token %}
            <input type="submit" id="DonorInfo" value="DonorInfo"></input>
          </form>
        </li>
      </ul>
      </nav>

      <article>
        <h1>Login</h1>
        <p>“It’s a great honor,” said Fedyor. “To save a life. You saved many.” </p>
        <p>“We were meant to rescue each other, not cut down the forest to rescue one.”</p>
      </article>
    </section>
  </body>
</html>